# Generated by Django 4.1.4 on 2024-09-22 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('idAccessoire', models.AutoField(primary_key=True, serialize=False)),
                ('Details', models.CharField(max_length=45)),
                ('Prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stockage', models.CharField(max_length=45)),
                ('Quantite', models.IntegerField()),
                ('Date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Accessoire',
                'verbose_name_plural': 'Accessoires',
                'db_table': 'Accessoire',
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('idAdministrateur', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
                'db_table': 'Administrateur',
            },
        ),
        migrations.CreateModel(
            name='Batterie',
            fields=[
                ('idBatterie', models.AutoField(primary_key=True, serialize=False)),
                ('Details', models.CharField(max_length=45)),
                ('Prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stockage', models.CharField(max_length=45)),
                ('Quantite', models.IntegerField()),
                ('Date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Batterie',
                'verbose_name_plural': 'Batteries',
                'db_table': 'Batterie',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=45)),
                ('Contact', models.CharField(max_length=45)),
                ('Statut', models.BooleanField(default=True)),
                ('etat_compte', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('idFournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=45)),
                ('Contact', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'Fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('idHistorique', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Achat', models.DateTimeField()),
                ('Designation', models.CharField(max_length=45)),
                ('Montant_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Montant_Paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Montant_Restant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'db_table': 'Historique',
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('idMArque', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=45)),
                ('Quantite', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'db_table': 'Marque',
            },
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('idNature', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=45)),
            ],
            options={
                'verbose_name': 'Nature',
                'verbose_name_plural': 'Natures',
                'db_table': 'Nature',
            },
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('idNumero', models.AutoField(primary_key=True, serialize=False)),
                ('Numero', models.CharField(max_length=45)),
                ('Quantite', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Numero',
                'verbose_name_plural': 'Numeros',
                'db_table': 'Numero',
            },
        ),
        migrations.CreateModel(
            name='Pneu',
            fields=[
                ('idPneu', models.AutoField(primary_key=True, serialize=False)),
                ('Details', models.CharField(max_length=45)),
                ('Prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stockage', models.CharField(max_length=45)),
                ('Quantite', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fournisseur')),
                ('Marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.marque')),
                ('Numero', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.numero')),
            ],
            options={
                'verbose_name': 'Pneu',
                'verbose_name_plural': 'Pneus',
                'db_table': 'Pneu',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('idTransaction', models.AutoField(primary_key=True, serialize=False)),
                ('Details', models.CharField(max_length=45)),
                ('Prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stockage', models.CharField(max_length=45)),
                ('Quantite', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fournisseur')),
                ('Marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.marque')),
                ('Nature', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.nature')),
                ('Numero', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.numero')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='PneuHistorique',
            fields=[
                ('idPneuHistorique', models.AutoField(primary_key=True, serialize=False)),
                ('Historique_idHistorique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.historique')),
                ('Pneu_Numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pneu')),
            ],
            options={
                'verbose_name': 'PneuHistorique',
                'verbose_name_plural': 'PneuHistorique',
                'db_table': 'PneuHistorique',
            },
        ),
        migrations.CreateModel(
            name='BatterieHistorique',
            fields=[
                ('idBatterieHistorique', models.AutoField(primary_key=True, serialize=False)),
                ('Batterie_Numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.batterie')),
                ('Historique_idHistorique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.historique')),
            ],
            options={
                'verbose_name': 'BatterieHistorique',
                'verbose_name_plural': 'BatterieHistorique',
                'db_table': 'BatterieHistorique',
            },
        ),
        migrations.AddField(
            model_name='batterie',
            name='Fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fournisseur'),
        ),
        migrations.AddField(
            model_name='batterie',
            name='Marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.marque'),
        ),
        migrations.AddField(
            model_name='batterie',
            name='Numero',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.numero'),
        ),
        migrations.CreateModel(
            name='AccessoireHistorique',
            fields=[
                ('idAccessoireHistorique', models.AutoField(primary_key=True, serialize=False)),
                ('Accesoire_Numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.accessoire')),
                ('Historique_idHistorique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.historique')),
            ],
            options={
                'verbose_name': 'AccessoireHistorique',
                'verbose_name_plural': 'AccessoireHistorique',
                'db_table': 'AccessoireHistorique',
            },
        ),
        migrations.AddField(
            model_name='accessoire',
            name='Fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fournisseur'),
        ),
        migrations.AddField(
            model_name='accessoire',
            name='Marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.marque'),
        ),
        migrations.AddField(
            model_name='accessoire',
            name='Numero',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.numero'),
        ),
    ]
